function remote_init()
	local items = {
		{name="Fader 1", input="value", min=0, max=127},
		{name="Fader 2", input="value", min=0, max=127},
		{name="Fader 3", input="value", min=0, max=127},
		{name="Fader 4", input="value", min=0, max=127},
		{name="Fader 5", input="value", min=0, max=127},
		{name="Fader 6", input="value", min=0, max=127},
		{name="Fader 7", input="value", min=0, max=127},
		{name="Fader 8", input="value", min=0, max=127},
		{name="Master Fader", input="value", min=0, max=127},
		{name="Knob 1A", input="value", min=0, max=127},
		{name="Knob 1B", input="value", min=0, max=127},
		{name="Knob 1C", input="value", min=0, max=127},
		{name="Knob 2A", input="value", min=0, max=127},
		{name="Knob 2B", input="value", min=0, max=127},
		{name="Knob 2C", input="value", min=0, max=127},
		{name="Knob 3A", input="value", min=0, max=127},
		{name="Knob 3B", input="value", min=0, max=127},
		{name="Knob 3C", input="value", min=0, max=127},
		{name="Knob 4A", input="value", min=0, max=127},
		{name="Knob 4B", input="value", min=0, max=127},
		{name="Knob 4C", input="value", min=0, max=127},
		{name="Knob 5A", input="value", min=0, max=127},
		{name="Knob 5B", input="value", min=0, max=127},
		{name="Knob 5C", input="value", min=0, max=127},
		{name="Knob 6A", input="value", min=0, max=127},
		{name="Knob 6B", input="value", min=0, max=127},
		{name="Knob 6C", input="value", min=0, max=127},
		{name="Knob 7A", input="value", min=0, max=127},
		{name="Knob 7B", input="value", min=0, max=127},
		{name="Knob 7C", input="value", min=0, max=127},
		{name="Knob 8A", input="value", min=0, max=127},
		{name="Knob 8B", input="value", min=0, max=127},
		{name="Knob 8C", input="value", min=0, max=127},
		{name="Mute Button 1", input="button", output="value"},
		{name="Mute Button 2", input="button", output="value"},
		{name="Mute Button 3", input="button", output="value"},
		{name="Mute Button 4", input="button", output="value"},
		{name="Mute Button 5", input="button", output="value"},
		{name="Mute Button 6", input="button", output="value"},
		{name="Mute Button 7", input="button", output="value"},
		{name="Mute Button 8", input="button", output="value"},
		{name="Solo Button", input="button"},
		{name="Rec Arm Button 1", input="button", output="value"},
		{name="Rec Arm Button 2", input="button", output="value"},
		{name="Rec Arm Button 3", input="button", output="value"},
		{name="Rec Arm Button 4", input="button", output="value"},
		{name="Rec Arm Button 5", input="button", output="value"},
		{name="Rec Arm Button 6", input="button", output="value"},
		{name="Rec Arm Button 7", input="button", output="value"},
		{name="Rec Arm Button 8", input="button", output="value"},
		{name="Bank Left Button", input="button"},
		{name="Bank Right Button", input="button"},		
	}
	remote.define_items(items)

	local inputs={
		{pattern="b0 13 xx", name="Fader 1"},
		{pattern="b0 17 xx", name="Fader 2"},
		{pattern="b0 1b xx", name="Fader 3"},
		{pattern="b0 1f xx", name="Fader 4"},
		{pattern="b0 31 xx", name="Fader 5"},
		{pattern="b0 35 xx", name="Fader 6"},
		{pattern="b0 39 xx", name="Fader 7"},
		{pattern="b0 3d xx", name="Fader 8"},
		{pattern="b0 3e xx", name="Master Fader"},	
		{pattern="b0 10 xx", name="Knob 1A"},
		{pattern="b0 11 xx", name="Knob 1B"},
		{pattern="b0 12 xx", name="Knob 1C"},
		{pattern="b0 14 xx", name="Knob 2A"},
		{pattern="b0 15 xx", name="Knob 2B"},
		{pattern="b0 16 xx", name="Knob 2C"},
		{pattern="b0 18 xx", name="Knob 3A"},
		{pattern="b0 19 xx", name="Knob 3B"},
		{pattern="b0 1a xx", name="Knob 3C"},
		{pattern="b0 1c xx", name="Knob 4A"},
		{pattern="b0 1d xx", name="Knob 4B"},
		{pattern="b0 1e xx", name="Knob 4C"},
		{pattern="b0 2e xx", name="Knob 5A"},
		{pattern="b0 2f xx", name="Knob 5B"},
		{pattern="b0 30 xx", name="Knob 5C"},
		{pattern="b0 32 xx", name="Knob 6A"},
		{pattern="b0 33 xx", name="Knob 6B"},
		{pattern="b0 34 xx", name="Knob 6C"},
		{pattern="b0 36 xx", name="Knob 7A"},
		{pattern="b0 37 xx", name="Knob 7B"},
		{pattern="b0 38 xx", name="Knob 7C"},
		{pattern="b0 3a xx", name="Knob 8A"},
		{pattern="b0 3b xx", name="Knob 8B"},
		{pattern="b0 3c xx", name="Knob 8C"},
		{pattern="90 01", name="Mute Button 1", value="1"},
		{pattern="90 04", name="Mute Button 2", value="1"},
		{pattern="90 07", name="Mute Button 3", value="1"},
		{pattern="90 0a", name="Mute Button 4", value="1"},
		{pattern="90 0d", name="Mute Button 5", value="1"},
		{pattern="90 10", name="Mute Button 6", value="1"},
		{pattern="90 13", name="Mute Button 7", value="1"},
		{pattern="90 16", name="Mute Button 8", value="1"},
		{pattern="90 1b", name="Solo Button", value="1"},
		{pattern="90 03", name="Rec Arm Button 1", value="1"},
		{pattern="90 06", name="Rec Arm Button 2", value="1"},
		{pattern="90 09", name="Rec Arm Button 3", value="1"},
		{pattern="90 0c", name="Rec Arm Button 4", value="1"},
		{pattern="90 0f", name="Rec Arm Button 5", value="1"},
		{pattern="90 12", name="Rec Arm Button 6", value="1"},
		{pattern="90 15", name="Rec Arm Button 7", value="1"},
		{pattern="90 18", name="Rec Arm Button 8", value="1"},
		{pattern="90 19", name="Bank Left Button", value="1"},
		{pattern="90 1a", name="Bank Right Button", value="1"},
	}
	remote.define_auto_inputs(inputs)

	local outputs={
		{pattern="90 01 xx", name="Mute Button 1", x="127*value"},
		{pattern="90 04 xx", name="Mute Button 2", x="127*value"},
		{pattern="90 07 xx", name="Mute Button 3", x="127*value"},
		{pattern="90 0a xx", name="Mute Button 4", x="127*value"},
		{pattern="90 0d xx", name="Mute Button 5", x="127*value"},
		{pattern="90 10 xx", name="Mute Button 6", x="127*value"},
		{pattern="90 13 xx", name="Mute Button 7", x="127*value"},
		{pattern="90 16 xx", name="Mute Button 8", x="127*value"},
		{pattern="90 03 xx", name="Rec Arm Button 1", x="127*value"},
		{pattern="90 06 xx", name="Rec Arm Button 2", x="127*value"},
		{pattern="90 09 xx", name="Rec Arm Button 3", x="127*value"},
		{pattern="90 0c xx", name="Rec Arm Button 4", x="127*value"},
		{pattern="90 0f xx", name="Rec Arm Button 5", x="127*value"},
		{pattern="90 12 xx", name="Rec Arm Button 6", x="127*value"},
		{pattern="90 15 xx", name="Rec Arm Button 7", x="127*value"},
		{pattern="90 18 xx", name="Rec Arm Button 8", x="127*value"},
	}
	remote.define_auto_outputs(outputs)
end